import { router } from 'expo-router';
import * as Linking from 'expo-linking';
import { useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { AuthField } from '@/components/AuthField';
import { AuthScreen } from '@/components/AuthScreen';
import { supabase } from '@/lib/supabase';
import { colors, fonts } from '@/theme';

export default function ForgotPasswordScreen(){const[email,setEmail]=useState('');const[message,setMessage]=useState<string|null>(null);const[sent,setSent]=useState(false);const[loading,setLoading]=useState(false);async function send(){if(!email.includes('@')){setMessage('Enter a valid email address.');return;}setLoading(true);setMessage(null);const{error}=await supabase.auth.resetPasswordForEmail(email.trim().toLowerCase(),{redirectTo:Linking.createURL('/reset-password')});setLoading(false);if(error){setMessage(error.message);return;}setSent(true);}return <AuthScreen eyebrow="Account recovery" title={sent?'Check your inbox':'Reset your password'} description={sent?`If an account exists for ${email.trim().toLowerCase()}, a reset link is on its way.`:'Enter the email address connected to your GWMB account.'}>{sent?<View style={styles.sent}><Text style={styles.sentMark}>✓</Text><Text style={styles.sentCopy}>Open the email on this device and follow the secure reset link.</Text></View>:<><AuthField label="Email address" value={email} onChangeText={setEmail} placeholder="you@example.com" keyboardType="email-address" autoComplete="email"/>{message?<View style={styles.message}><Text style={styles.messageText}>{message}</Text></View>:null}<Pressable disabled={loading} onPress={send} style={[styles.submit,loading&&styles.disabled]}>{loading?<ActivityIndicator color="white"/>:<Text style={styles.submitText}>Send reset link</Text>}</Pressable></>}<Pressable onPress={()=>router.replace('/sign-in')} style={styles.back}><Text style={styles.backText}>Back to sign in</Text></Pressable></AuthScreen>}
const styles=StyleSheet.create({message:{borderRadius:12,backgroundColor:'#FFF0F3',padding:11},messageText:{color:'#A31D43',fontSize:10,fontFamily:fonts.body},submit:{minHeight:54,borderRadius:16,backgroundColor:colors.pinkDeep,alignItems:'center',justifyContent:'center',marginTop:16},disabled:{opacity:.6},submitText:{color:'white',fontSize:13,fontFamily:fonts.bodyBold},back:{alignItems:'center',paddingVertical:19},backText:{color:colors.pinkDeep,fontSize:11,fontFamily:fonts.bodyBold},sent:{borderRadius:21,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,padding:22,alignItems:'center'},sentMark:{width:50,height:50,borderRadius:25,backgroundColor:colors.pinkSoft,color:colors.pinkDeep,fontSize:24,fontFamily:fonts.heading,lineHeight:50,textAlign:'center'},sentCopy:{color:colors.muted,fontSize:11,lineHeight:18,fontFamily:fonts.body,textAlign:'center',marginTop:13}});
