import { router } from 'expo-router';
import * as Linking from 'expo-linking';
import { useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { AuthField } from '@/components/AuthField';
import { AuthScreen } from '@/components/AuthScreen';
import { supabase } from '@/lib/supabase';
import { colors, fonts } from '@/theme';

export default function SignUpScreen(){const[name,setName]=useState('');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[message,setMessage]=useState<string|null>(null);const[success,setSuccess]=useState(false);const[submitting,setSubmitting]=useState(false);async function signUp(){setMessage(null);if(name.trim().length<2){setMessage('Enter your full name.');return;}if(!email.includes('@')){setMessage('Enter a valid email address.');return;}if(password.length<8){setMessage('Use at least 8 characters for your password.');return;}setSubmitting(true);const{data,error}=await supabase.auth.signUp({email:email.trim().toLowerCase(),password,options:{data:{full_name:name.trim()},emailRedirectTo:Linking.createURL('/welcome')}});setSubmitting(false);if(error){setMessage(error.message);return;}if(data.session){router.replace('/');return;}setSuccess(true);}if(success)return <AuthScreen eyebrow="One more step" title="Check your inbox" description={`We sent a verification link to ${email.trim().toLowerCase()}.`}><View style={styles.successCard}><Text style={styles.successIcon}>✓</Text><Text style={styles.successTitle}>Confirm your email</Text><Text style={styles.successCopy}>After confirming, return to GWMB and sign in. Your account starts with Guest access until membership is verified.</Text></View><Pressable onPress={()=>router.replace('/sign-in')} style={styles.submit}><Text style={styles.submitText}>Go to sign in</Text></Pressable></AuthScreen>;return <AuthScreen eyebrow="Join the experience" title="Create your account" description="Start with Guest access. Existing GWMB members can verify membership after signing in."><AuthField label="Full name" value={name} onChangeText={setName} placeholder="Your full name" autoCapitalize="words" autoComplete="name"/><AuthField label="Email address" value={email} onChangeText={setEmail} placeholder="you@example.com" keyboardType="email-address" autoComplete="email"/><AuthField label="Password" value={password} onChangeText={setPassword} placeholder="At least 8 characters" password autoComplete="new-password"/>{message?<View style={styles.message}><Text style={styles.messageText}>{message}</Text></View>:null}<Pressable disabled={submitting} onPress={signUp} style={[styles.submit,submitting&&styles.disabled]}>{submitting?<ActivityIndicator color="white"/>:<Text style={styles.submitText}>Create account</Text>}</Pressable><Text style={styles.terms}>By creating an account, you agree to GWMB’s Terms and Privacy Policy.</Text><Pressable onPress={()=>router.replace('/sign-in')} style={styles.switch}><Text style={styles.switchText}>Already have an account? <Text style={styles.switchStrong}>Sign in</Text></Text></Pressable></AuthScreen>}
const styles=StyleSheet.create({message:{borderRadius:12,backgroundColor:'#FFF0F3',padding:11,marginTop:2},messageText:{color:'#A31D43',fontSize:10,lineHeight:15,fontFamily:fonts.body},submit:{minHeight:54,borderRadius:16,backgroundColor:colors.pinkDeep,alignItems:'center',justifyContent:'center',marginTop:17},disabled:{opacity:.6},submitText:{color:'white',fontSize:13,fontFamily:fonts.bodyBold},terms:{color:colors.muted,fontSize:9,lineHeight:14,fontFamily:fonts.body,textAlign:'center',marginTop:12,paddingHorizontal:15},switch:{alignItems:'center',paddingVertical:19},switchText:{color:colors.muted,fontSize:11,fontFamily:fonts.body},switchStrong:{color:colors.pinkDeep,fontFamily:fonts.bodyBold},successCard:{borderRadius:22,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,padding:22,alignItems:'center'},successIcon:{width:52,height:52,borderRadius:26,backgroundColor:colors.pinkSoft,color:colors.pinkDeep,textAlign:'center',fontSize:25,fontFamily:fonts.heading,lineHeight:52},successTitle:{color:colors.ink,fontSize:18,fontFamily:fonts.heading,marginTop:15},successCopy:{color:colors.muted,fontSize:11,lineHeight:18,fontFamily:fonts.body,textAlign:'center',marginTop:8}});
