import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { PageHeader } from '@/components/PageHeader';
import { Screen } from '@/components/Screen';
import { colors, fonts } from '@/theme';

const resources:Record<string,{type:string;title:string;copy:string;meta:string;points:string[]}>= {
  'weekly-planning':{type:'Practical Resource',title:'The Weekly Planning Template',copy:'A simple reusable template for turning priorities into a realistic week you can actually follow.',meta:'PDF · 5 pages',points:['Choose three weekly priorities','Plan realistic focus blocks','Protect rest and recovery','Review and reset each week']},
  'better-goals':{type:'Personal Growth Guide',title:'A Better Way to Set Goals',copy:'Make your next goal specific, workable and connected to an action you can take now.',meta:'8 min read',points:['Define a meaningful outcome','Choose the smallest next action','Set a realistic check-in rhythm','Review progress without judgement']},
  'conflict-guide':{type:'Leadership Guide',title:'Communicating Through Conflict',copy:'A practical guide to direct, respectful conversations when expectations or perspectives differ.',meta:'Guide · 12 min',points:['Prepare for the conversation','Separate facts from assumptions','Communicate clearly and calmly','Agree on a useful next step']},
};

export default function ResourceDetail(){const{id}=useLocalSearchParams<{id:string}>();const item=resources[id]??resources['weekly-planning'];return <Screen><PageHeader title="Resource" eyebrow={item.type}/><View style={styles.media}><View style={styles.orbit}/><Text style={styles.mediaTag}>GWMB RESOURCE</Text><Text style={styles.mediaTitle}>{item.title}</Text><Ionicons name="document-text-outline" size={42} color="white"/></View><Text style={styles.title}>About this resource</Text><Text style={styles.copy}>{item.copy}</Text><View style={styles.meta}><Ionicons name="time-outline" size={18} color={colors.pinkDeep}/><Text style={styles.metaText}>{item.meta} · Open Access</Text></View><Text style={styles.sectionTitle}>Inside the resource</Text><View style={styles.points}>{item.points.map(point=><View key={point} style={styles.point}><Ionicons name="checkmark" size={15} color={colors.pinkDeep}/><Text style={styles.pointText}>{point}</Text></View>)}</View><Pressable style={styles.cta}><Text style={styles.ctaText}>Open resource</Text><Ionicons name="arrow-forward" size={18} color="white"/></Pressable></Screen>}

const styles=StyleSheet.create({media:{height:235,borderRadius:24,backgroundColor:'#7040A0',padding:21,justifyContent:'space-between',overflow:'hidden'},orbit:{position:'absolute',right:-32,top:-42,width:155,height:155,borderRadius:78,borderWidth:28,borderColor:'rgba(255,255,255,.13)'},mediaTag:{color:'rgba(255,255,255,.8)',fontSize:8,fontFamily:fonts.bodyBold,letterSpacing:1.1},mediaTitle:{color:'white',fontSize:27,lineHeight:30,fontFamily:fonts.heading,letterSpacing:-.9,maxWidth:290},title:{color:colors.ink,fontSize:21,fontFamily:fonts.heading,marginTop:24},copy:{color:colors.muted,fontSize:12,lineHeight:19,fontFamily:fonts.body,marginTop:8},meta:{minHeight:52,borderRadius:16,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:14,marginTop:18},metaText:{color:colors.ink,fontSize:10,fontFamily:fonts.bodyBold},sectionTitle:{color:colors.ink,fontSize:17,fontFamily:fonts.headingBold,marginTop:25,marginBottom:10},points:{gap:8},point:{minHeight:48,borderRadius:15,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,paddingHorizontal:13,flexDirection:'row',gap:10,alignItems:'center'},pointText:{color:colors.ink,fontSize:10,fontFamily:fonts.bodyMedium},cta:{minHeight:54,borderRadius:16,backgroundColor:colors.pinkDeep,paddingHorizontal:17,flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:20},ctaText:{color:'white',fontSize:12,fontFamily:fonts.bodyBold}});
