import { Ionicons } from '@expo/vector-icons';
import { router as expoRouter, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

import { AuthField } from '@/components/AuthField';
import { PageHeader } from '@/components/PageHeader';
import { Screen } from '@/components/Screen';
import { opportunityById } from '@/data/opportunities';
import { submitOpportunityApplication } from '@/lib/opportunity-store';
import { useAuth } from '@/providers/AuthProvider';
import { colors, fonts } from '@/theme';

const router={push:(href:string)=>expoRouter.push(href as never),replace:(href:string)=>expoRouter.replace(href as never)};

export default function OpportunityApplication(){
  const{opportunityId}=useLocalSearchParams<{opportunityId:string}>();
  const{user}=useAuth();
  const item=opportunityById[opportunityId]??opportunityById['women-tech'];
  const[link,setLink]=useState(''); const[motivation,setMotivation]=useState(''); const[message,setMessage]=useState<string|null>(null); const[submitting,setSubmitting]=useState(false); const[success,setSuccess]=useState(false); const[cloud,setCloud]=useState(true);
  async function submit(){setMessage(null);if(!user){router.push('/sign-in');return;}if(motivation.trim().length<30){setMessage('Tell us a little more—your motivation should be at least 30 characters.');return;}if(link&&!(link.startsWith('http://')||link.startsWith('https://'))){setMessage('Enter a full link beginning with https://');return;}setSubmitting(true);const result=await submitOpportunityApplication({userId:user.id,opportunityId:item.id,portfolioUrl:link.trim(),motivation:motivation.trim()});setSubmitting(false);if(!result.ok&&result.duplicate){setMessage('You have already applied for this opportunity. View it under My Applications.');return;}if(result.ok){setCloud(result.cloud);setSuccess(true);}}
  if(success)return <Screen><PageHeader title="Application submitted"/><View style={styles.success}><View style={styles.successIcon}><Ionicons name="checkmark" size={30} color="white"/></View><Text style={styles.successTitle}>Your application is in.</Text><Text style={styles.successCopy}>We’ve added {item.title} to My Applications. You’ll see every status update there.</Text>{!cloud?<View style={styles.deviceNote}><Ionicons name="phone-portrait-outline" size={17} color={colors.pinkDeep}/><Text style={styles.deviceNoteText}>Preview mode: saved on this device. Apply the included Supabase migration to sync across devices.</Text></View>:null}<Pressable onPress={()=>router.replace('/opportunities?tab=applications')} style={styles.cta}><Text style={styles.ctaText}>View My Applications</Text><Ionicons name="arrow-forward" size={18} color="white"/></Pressable></View></Screen>;
  if(!user)return <Screen><PageHeader title="Apply"/><View style={styles.signIn}><View style={styles.signInIcon}><Ionicons name="lock-closed-outline" size={25} color={colors.pinkDeep}/></View><Text style={styles.signInTitle}>Sign in before applying</Text><Text style={styles.signInCopy}>Applications are private and must be connected to your GWMB account.</Text><Pressable onPress={()=>router.push('/sign-in')} style={styles.cta}><Text style={styles.ctaText}>Sign in to continue</Text><Ionicons name="arrow-forward" size={18} color="white"/></Pressable></View></Screen>;
  return <Screen><PageHeader title="Apply" eyebrow="Opportunity application"/><View style={styles.summary}><View style={styles.logo}><Text style={styles.logoText}>{item.initials}</Text></View><View style={styles.summaryCopy}><Text style={styles.org}>{item.org}</Text><Text style={styles.summaryTitle}>{item.title}</Text></View></View><Text style={styles.title}>Tell us about your interest</Text><Text style={styles.copy}>Review your details carefully. You can submit only one application for this opportunity.</Text><View style={styles.form}><AuthField label="LinkedIn or portfolio link (optional)" value={link} onChangeText={setLink} placeholder="https://" autoCapitalize="none" keyboardType="url"/><Text style={styles.label}>Motivation</Text><View style={[styles.textarea,message&&motivation.trim().length<30?styles.fieldError:null]}><TextInput value={motivation} onChangeText={setMotivation} placeholder="Why are you interested, and what would you bring?" placeholderTextColor="#A59FA3" multiline maxLength={2000} textAlignVertical="top" style={styles.textareaInput}/><Text style={styles.counter}>{motivation.length}/2000</Text></View></View><View style={styles.review}><Ionicons name="shield-checkmark-outline" size={20} color={colors.pinkDeep}/><Text style={styles.reviewText}>Your application is private and visible only to you and authorised GWMB reviewers.</Text></View>{message?<View style={styles.message}><Text style={styles.messageText}>{message}</Text>{message.includes('already applied')?<Pressable onPress={()=>router.replace('/opportunities?tab=applications')}><Text style={styles.messageAction}>View My Applications</Text></Pressable>:null}</View>:null}<Pressable disabled={submitting} onPress={()=>void submit()} style={[styles.cta,submitting&&styles.disabled]}>{submitting?<ActivityIndicator color="white"/>:<><Text style={styles.ctaText}>Submit application</Text><Ionicons name="arrow-forward" size={18} color="white"/></>}</Pressable></Screen>;
}

const styles=StyleSheet.create({summary:{borderRadius:20,backgroundColor:colors.ink,padding:15,flexDirection:'row',alignItems:'center'},logo:{width:48,height:48,borderRadius:15,backgroundColor:'white',alignItems:'center',justifyContent:'center'},logoText:{color:colors.pinkDeep,fontSize:13,fontFamily:fonts.heading},summaryCopy:{flex:1,paddingLeft:12},org:{color:'#F09AC2',fontSize:9,fontFamily:fonts.bodyBold},summaryTitle:{color:'white',fontSize:13,fontFamily:fonts.headingBold,marginTop:4},title:{color:colors.ink,fontSize:23,fontFamily:fonts.heading,marginTop:23},copy:{color:colors.muted,fontSize:11,lineHeight:18,fontFamily:fonts.body,marginTop:7},form:{marginTop:22},label:{color:colors.ink,fontSize:11,fontFamily:fonts.bodyBold,marginBottom:7},textarea:{height:145,borderRadius:15,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,padding:14},fieldError:{borderColor:'#D33A61'},textareaInput:{flex:1,color:colors.ink,fontSize:12,lineHeight:18,fontFamily:fonts.body,padding:0},counter:{alignSelf:'flex-end',fontSize:9,fontFamily:fonts.body,color:colors.muted},review:{borderRadius:17,backgroundColor:colors.pinkSoft,padding:14,flexDirection:'row',gap:10,marginTop:17},reviewText:{flex:1,color:colors.muted,fontSize:9,lineHeight:15,fontFamily:fonts.body},message:{borderRadius:14,backgroundColor:'#FFF0F3',padding:12,marginTop:13},messageText:{color:'#A31D43',fontSize:9,lineHeight:15,fontFamily:fonts.body},messageAction:{color:colors.pinkDeep,fontSize:9,fontFamily:fonts.bodyBold,marginTop:7},cta:{minHeight:54,borderRadius:16,backgroundColor:colors.pinkDeep,paddingHorizontal:17,flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:18},ctaText:{color:'white',fontSize:11,fontFamily:fonts.bodyBold},disabled:{opacity:.6},success:{marginTop:35,alignItems:'center'},successIcon:{width:70,height:70,borderRadius:24,backgroundColor:colors.pinkDeep,alignItems:'center',justifyContent:'center'},successTitle:{color:colors.ink,fontSize:25,fontFamily:fonts.heading,textAlign:'center',marginTop:19},successCopy:{color:colors.muted,fontSize:10,lineHeight:17,fontFamily:fonts.body,textAlign:'center',marginTop:7,maxWidth:310},deviceNote:{borderRadius:16,backgroundColor:colors.pinkSoft,padding:13,flexDirection:'row',gap:9,marginTop:18},deviceNoteText:{flex:1,color:colors.muted,fontSize:9,lineHeight:13,fontFamily:fonts.body},signIn:{marginTop:35,alignItems:'center',padding:22,borderRadius:24,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line},signInIcon:{width:62,height:62,borderRadius:21,backgroundColor:colors.pinkSoft,alignItems:'center',justifyContent:'center'},signInTitle:{color:colors.ink,fontSize:21,fontFamily:fonts.heading,textAlign:'center',marginTop:17},signInCopy:{color:colors.muted,fontSize:10,lineHeight:16,fontFamily:fonts.body,textAlign:'center',marginTop:7}});
