import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, Share, StyleSheet, Text, View } from 'react-native';

import { PageHeader } from '@/components/PageHeader';
import { Screen } from '@/components/Screen';
import { courses } from '@/data/courses';
import { coursePercent, loadCourseProgress, type CourseProgress } from '@/lib/course-progress';
import { useAuth } from '@/providers/AuthProvider';
import { colors, fonts } from '@/theme';

export default function Certificate(){
  const{courseId}=useLocalSearchParams<{courseId:string}>(); const course=courses[courseId]??courses['workplace-foundations']; const{user,profile}=useAuth(); const[progress,setProgress]=useState<CourseProgress|null>(null); const[loading,setLoading]=useState(Boolean(user));
  useEffect(()=>{if(!user)return;loadCourseProgress(user.id,course.id).then(result=>{setProgress(result.progress);setLoading(false)});},[course.id,user]);
  const percent=coursePercent(progress,course.lessons.length); const name=profile?.full_name||user?.email?.split('@')[0]||'GWMB Learner'; const date=progress?.completed_at?new Date(progress.completed_at).toLocaleDateString(undefined,{day:'numeric',month:'long',year:'numeric'}):''; const reference=`GWMB-${course.id.slice(0,3).toUpperCase()}-${user?.id.slice(0,6).toUpperCase()??'PREVIEW'}`;
  if(loading)return <Screen scroll={false}><View style={styles.loading}><ActivityIndicator color={colors.pinkDeep}/></View></Screen>;
  if(percent<100)return <Screen><PageHeader title="Certificate"/><View style={styles.locked}><View style={styles.lockedIcon}><Ionicons name="lock-closed-outline" size={27} color={colors.pinkDeep}/></View><Text style={styles.lockedTitle}>Your certificate is still locked</Text><Text style={styles.lockedCopy}>Complete all {course.lessons.length} lessons to unlock your GWMB certificate. You’re currently {percent}% complete.</Text><Pressable onPress={()=>router.replace(`/course/${course.id}`)} style={styles.primary}><Text style={styles.primaryText}>Continue course</Text><Ionicons name="arrow-forward" size={18} color="white"/></Pressable></View></Screen>;
  return <Screen><PageHeader title="Certificate" eyebrow="Course complete"/><View style={styles.certificate}><View style={styles.corner}/><View style={styles.ribbon}><Ionicons name="ribbon" size={28} color="white"/></View><Text style={styles.brand}>GWMB</Text><Text style={styles.kicker}>CERTIFICATE OF COMPLETION</Text><Text style={styles.presented}>This certificate is proudly presented to</Text><Text style={styles.name}>{name}</Text><View style={styles.rule}/><Text style={styles.forText}>for successfully completing</Text><Text style={styles.course}>{course.title}</Text><View style={styles.details}><View><Text style={styles.detailLabel}>COMPLETED</Text><Text style={styles.detailValue}>{date}</Text></View><View><Text style={styles.detailLabel}>REFERENCE</Text><Text style={styles.detailValue}>{reference}</Text></View></View><Text style={styles.signature}>Girls Who Mean Business</Text><Text style={styles.signatureLabel}>Preparing Africa’s next generation of female talent</Text></View><Pressable onPress={()=>Share.share({message:`I completed “${course.title}” with Girls Who Mean Business. Certificate: ${reference}`})} style={styles.primary}><Text style={styles.primaryText}>Share achievement</Text><Ionicons name="share-social-outline" size={18} color="white"/></Pressable><Pressable onPress={()=>router.replace('/')} style={styles.secondary}><Text style={styles.secondaryText}>Return home</Text></Pressable></Screen>;
}

const styles=StyleSheet.create({loading:{flex:1,alignItems:'center',justifyContent:'center'},certificate:{minHeight:540,borderRadius:27,backgroundColor:colors.surface,borderWidth:1,borderColor:'#E8D9E0',padding:24,alignItems:'center',justifyContent:'center',overflow:'hidden'},corner:{position:'absolute',width:180,height:180,borderRadius:90,borderWidth:30,borderColor:colors.pinkSoft,right:-68,top:-70},ribbon:{width:61,height:61,borderRadius:21,backgroundColor:colors.pinkDeep,alignItems:'center',justifyContent:'center'},brand:{color:colors.ink,fontSize:15,fontFamily:fonts.heading,letterSpacing:2,marginTop:18},kicker:{color:colors.pinkDeep,fontSize:9,fontFamily:fonts.bodyBold,letterSpacing:1.3,marginTop:5},presented:{color:colors.muted,fontSize:9,fontFamily:fonts.body,marginTop:35},name:{color:colors.ink,fontSize:27,fontFamily:fonts.heading,textAlign:'center',textTransform:'capitalize',marginTop:8},rule:{width:90,height:2,backgroundColor:colors.pink,marginTop:12},forText:{color:colors.muted,fontSize:9,fontFamily:fonts.body,marginTop:25},course:{color:colors.ink,fontSize:17,lineHeight:22,fontFamily:fonts.headingBold,textAlign:'center',marginTop:7,maxWidth:300},details:{alignSelf:'stretch',flexDirection:'row',justifyContent:'space-between',borderTopWidth:1,borderTopColor:colors.line,marginTop:34,paddingTop:18},detailLabel:{color:colors.pinkDeep,fontSize:9,fontFamily:fonts.bodyBold,letterSpacing:.8},detailValue:{color:colors.ink,fontSize:9,fontFamily:fonts.bodyBold,marginTop:4},signature:{color:colors.ink,fontSize:11,fontFamily:fonts.headingBold,marginTop:34},signatureLabel:{color:colors.muted,fontSize:9,fontFamily:fonts.body,textAlign:'center',marginTop:3},primary:{minHeight:55,borderRadius:17,backgroundColor:colors.pinkDeep,paddingHorizontal:17,flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:20},primaryText:{color:'white',fontSize:11,fontFamily:fonts.bodyBold},secondary:{height:48,borderRadius:16,borderWidth:1,borderColor:colors.line,alignItems:'center',justifyContent:'center',marginTop:9},secondaryText:{color:colors.ink,fontSize:10,fontFamily:fonts.bodyBold},locked:{marginTop:35,alignItems:'center',padding:23,borderRadius:24,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line},lockedIcon:{width:65,height:65,borderRadius:22,backgroundColor:colors.pinkSoft,alignItems:'center',justifyContent:'center'},lockedTitle:{color:colors.ink,fontSize:21,fontFamily:fonts.heading,textAlign:'center',marginTop:17},lockedCopy:{color:colors.muted,fontSize:10,lineHeight:16,fontFamily:fonts.body,textAlign:'center',marginTop:7}});
