import { Ionicons } from '@expo/vector-icons';
import { router as expoRouter, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { PageHeader } from '@/components/PageHeader';
import { Screen } from '@/components/Screen';
import { courses } from '@/data/courses';
import { coursePercent, loadCourseProgress, type CourseProgress } from '@/lib/course-progress';
import { useAuth } from '@/providers/AuthProvider';
import { colors, fonts } from '@/theme';

const router={push:(href:string)=>expoRouter.push(href as never)};

export default function Activity(){
  const{user}=useAuth(); const userId=user?.id; const course=courses['workplace-foundations']; const[progress,setProgress]=useState<CourseProgress|null>(null);
  useFocusEffect(useCallback(()=>{let active=true;if(!userId){setProgress(null);return()=>{active=false};}loadCourseProgress(userId,course.id).then(result=>{if(active)setProgress(result.progress)});return()=>{active=false};},[course.id,userId]));
  const percent=coursePercent(progress,course.lessons.length); const currentIndex=Math.max(0,course.lessons.findIndex(item=>!progress?.completed_lesson_ids.includes(item.id))); const complete=percent===100;
  return <Screen><PageHeader title="My GWMB Activity"/><View style={styles.stats}><View><Text style={styles.number}>{percent}%</Text><Text style={styles.label}>Course progress</Text></View><View><Text style={styles.number}>{progress?.completed_lesson_ids.length??0}</Text><Text style={styles.label}>Lessons complete</Text></View><View><Text style={styles.number}>{complete?1:0}</Text><Text style={styles.label}>Certificates</Text></View></View><Text style={styles.section}>Continue learning</Text><Pressable onPress={()=>router.push('/course/workplace-foundations')} style={styles.row}><View style={styles.icon}><Ionicons name={complete?'ribbon':'play'} size={18} color="white"/></View><View style={styles.copy}><Text style={styles.title}>CV that gets noticed</Text><Text style={styles.meta}>{complete?'Complete · Certificate ready':progress?`Lesson ${currentIndex+1} of ${course.lessons.length} · ${percent}%`:'Ready to start · 6 lessons'}</Text></View><Ionicons name="arrow-forward" size={18} color={colors.ink}/></Pressable><Text style={styles.section}>Certificates</Text>{complete?<Pressable onPress={()=>router.push('/certificate/workplace-foundations')} style={styles.certificate}><View style={styles.certificateIcon}><Ionicons name="ribbon-outline" size={25} color={colors.pinkDeep}/></View><View style={styles.copy}><Text style={styles.title}>Build a CV that gets noticed</Text><Text style={styles.meta}>Certificate earned · Tap to view</Text></View><Ionicons name="chevron-forward" size={18} color={colors.muted}/></Pressable>:<View style={styles.empty}><Ionicons name="ribbon-outline" size={27} color={colors.pinkDeep}/><Text style={styles.emptyTitle}>Your certificates will appear here</Text><Text style={styles.emptyCopy}>Complete an eligible course to unlock its certificate.</Text></View>}</Screen>;
}
const styles=StyleSheet.create({stats:{borderRadius:22,backgroundColor:colors.ink,padding:18,flexDirection:'row',justifyContent:'space-between'},number:{color:'white',fontSize:20,fontFamily:fonts.heading},label:{color:'#BEB7BB',fontSize:9,fontFamily:fonts.body,marginTop:4},section:{color:colors.ink,fontSize:17,fontFamily:fonts.heading,marginTop:26,marginBottom:11},row:{minHeight:78,borderRadius:19,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,padding:13,flexDirection:'row',alignItems:'center'},icon:{width:44,height:44,borderRadius:14,backgroundColor:colors.pink,alignItems:'center',justifyContent:'center'},copy:{flex:1,paddingHorizontal:11},title:{color:colors.ink,fontSize:11,fontFamily:fonts.headingBold},meta:{color:colors.muted,fontSize:9,fontFamily:fonts.body,marginTop:4},empty:{borderRadius:20,backgroundColor:colors.pinkSoft,padding:22,alignItems:'center'},emptyTitle:{color:colors.ink,fontSize:12,fontFamily:fonts.headingBold,marginTop:10},emptyCopy:{color:colors.muted,fontSize:9,fontFamily:fonts.body,textAlign:'center',marginTop:5},certificate:{minHeight:75,borderRadius:19,borderWidth:1,borderColor:'#F0C6D9',backgroundColor:colors.blush,padding:13,flexDirection:'row',alignItems:'center'},certificateIcon:{width:44,height:44,borderRadius:14,backgroundColor:colors.pinkSoft,alignItems:'center',justifyContent:'center'}});
