import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { PageHeader } from '@/components/PageHeader';
import { Screen } from '@/components/Screen';
import { colors, fonts } from '@/theme';

export default function Goal(){return <Screen><PageHeader title="My goal" eyebrow="Personal Growth"/><View style={styles.hero}><View style={styles.icon}><Ionicons name="locate-outline" size={25} color="white"/></View><Text style={styles.title}>Create a meaningful goal</Text><Text style={styles.copy}>Keep it specific, private and connected to one next action you can actually take.</Text></View><Text style={styles.label}>WHAT IS YOUR GOAL?</Text><TextInput placeholder="A specific outcome" placeholderTextColor={colors.muted} style={styles.input}/><Text style={styles.label}>WHAT IS YOUR NEXT ACTION?</Text><TextInput placeholder="The smallest useful step" placeholderTextColor={colors.muted} multiline style={[styles.input,styles.notes]}/><View style={styles.row}><View style={styles.half}><Text style={styles.label}>TARGET DATE</Text><TextInput placeholder="30 Nov" placeholderTextColor={colors.muted} style={styles.input}/></View><View style={styles.half}><Text style={styles.label}>CHECK-IN</Text><TextInput placeholder="Weekly" placeholderTextColor={colors.muted} style={styles.input}/></View></View><Pressable onPress={()=>router.back()} style={styles.cta}><Text style={styles.ctaText}>Save my goal</Text><Ionicons name="arrow-forward" size={18} color="white"/></Pressable><Text style={styles.private}><Ionicons name="lock-closed" size={11}/> Your goal stays private to your account.</Text></Screen>}
const styles=StyleSheet.create({hero:{borderRadius:24,backgroundColor:'#6745D9',padding:21},icon:{width:48,height:48,borderRadius:16,backgroundColor:'rgba(255,255,255,.18)',alignItems:'center',justifyContent:'center'},title:{color:'white',fontSize:25,fontFamily:fonts.heading,marginTop:25},copy:{color:'rgba(255,255,255,.82)',fontSize:10,lineHeight:17,fontFamily:fonts.body,marginTop:7},label:{color:colors.ink,fontSize:9,fontFamily:fonts.bodyBold,letterSpacing:.7,marginTop:18,marginBottom:7},input:{height:53,borderRadius:16,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,paddingHorizontal:14,fontSize:10,fontFamily:fonts.body,color:colors.ink},notes:{height:95,paddingTop:14,textAlignVertical:'top'},row:{flexDirection:'row',gap:9},half:{flex:1},cta:{height:55,borderRadius:17,backgroundColor:colors.pinkDeep,paddingHorizontal:17,flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:23},ctaText:{color:'white',fontSize:12,fontFamily:fonts.bodyBold},private:{color:colors.muted,fontSize:9,fontFamily:fonts.body,textAlign:'center',marginTop:13}});
