import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { PageHeader } from '@/components/PageHeader';
import { Screen } from '@/components/Screen';
import { colors, fonts } from '@/theme';

export default function MentorshipApplication(){return <Screen><PageHeader title="Mentorship application"/><View style={styles.hero}><Text style={styles.kicker}>OCTOBER–DECEMBER COHORT</Text><Text style={styles.title}>Product & Technology Cohort</Text><Text style={styles.copy}>Three months of structured small-group guidance with working professionals.</Text><View style={styles.tags}>{['2 meetings monthly','10–15 mentees','Members only'].map(item=><View key={item} style={styles.tag}><Text style={styles.tagText}>{item}</Text></View>)}</View></View><Text style={styles.label}>YOUR CURRENT CAREER INTEREST</Text><TextInput placeholder="e.g. Product design" placeholderTextColor={colors.muted} style={styles.input}/><Text style={styles.label}>WHAT WOULD CLARITY LOOK LIKE FOR YOU?</Text><TextInput placeholder="Tell us what you hope to work through" placeholderTextColor={colors.muted} multiline style={[styles.input,styles.notes]}/><Text style={styles.label}>WHY IS THIS THE RIGHT TIME?</Text><TextInput placeholder="Share a short response" placeholderTextColor={colors.muted} multiline style={[styles.input,styles.notes]}/><Pressable onPress={()=>router.back()} style={styles.cta}><Text style={styles.ctaText}>Submit application</Text><Ionicons name="arrow-forward" size={18} color="white"/></Pressable><Text style={styles.note}>Applications are reviewed for programme fit and available capacity. Membership does not guarantee placement.</Text></Screen>}
const styles=StyleSheet.create({hero:{borderRadius:24,backgroundColor:colors.ink,padding:21},kicker:{color:'#F4A2C8',fontSize:9,fontFamily:fonts.bodyBold,letterSpacing:1},title:{color:'white',fontSize:25,lineHeight:29,fontFamily:fonts.heading,marginTop:8},copy:{color:'#D2CBD0',fontSize:10,lineHeight:17,fontFamily:fonts.body,marginTop:7},tags:{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:17},tag:{borderRadius:999,backgroundColor:'rgba(255,255,255,.12)',paddingHorizontal:9,paddingVertical:6},tagText:{color:'white',fontSize:9,fontFamily:fonts.bodyBold},label:{color:colors.ink,fontSize:9,fontFamily:fonts.bodyBold,letterSpacing:.7,marginTop:18,marginBottom:7},input:{height:53,borderRadius:16,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,paddingHorizontal:14,fontSize:10,fontFamily:fonts.body,color:colors.ink},notes:{height:94,paddingTop:14,textAlignVertical:'top'},cta:{height:55,borderRadius:17,backgroundColor:colors.pinkDeep,paddingHorizontal:17,flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:22},ctaText:{color:'white',fontSize:12,fontFamily:fonts.bodyBold},note:{color:colors.muted,fontSize:9,lineHeight:12,fontFamily:fonts.body,textAlign:'center',marginTop:12}});
