import { router } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { AuthField } from '@/components/AuthField';
import { AuthScreen } from '@/components/AuthScreen';
import { supabase } from '@/lib/supabase';
import { colors, fonts } from '@/theme';

export default function ResetPasswordScreen(){const[password,setPassword]=useState('');const[confirm,setConfirm]=useState('');const[message,setMessage]=useState<string|null>(null);const[loading,setLoading]=useState(false);const[complete,setComplete]=useState(false);async function update(){setMessage(null);if(password.length<8){setMessage('Use at least 8 characters for your password.');return;}if(password!==confirm){setMessage('The passwords do not match.');return;}setLoading(true);const{error}=await supabase.auth.updateUser({password});setLoading(false);if(error){setMessage(error.message);return;}setComplete(true);}if(complete)return <AuthScreen eyebrow="Password updated" title="You’re ready to continue" description="Your new password is active."><View style={styles.success}><Text style={styles.successMark}>✓</Text><Text style={styles.successText}>Your account is secure and ready.</Text></View><Pressable onPress={()=>router.replace('/')} style={styles.submit}><Text style={styles.submitText}>Continue to GWMB</Text></Pressable></AuthScreen>;return <AuthScreen eyebrow="Account recovery" title="Choose a new password" description="Create a secure password you have not used before."><AuthField label="New password" value={password} onChangeText={setPassword} placeholder="At least 8 characters" password autoComplete="new-password"/><AuthField label="Confirm new password" value={confirm} onChangeText={setConfirm} placeholder="Repeat your password" password autoComplete="new-password"/>{message?<View style={styles.message}><Text style={styles.messageText}>{message}</Text></View>:null}<Pressable disabled={loading} onPress={update} style={[styles.submit,loading&&styles.disabled]}>{loading?<ActivityIndicator color="white"/>:<Text style={styles.submitText}>Update password</Text>}</Pressable></AuthScreen>}
const styles=StyleSheet.create({message:{borderRadius:12,backgroundColor:'#FFF0F3',padding:11},messageText:{color:'#A31D43',fontSize:10,fontFamily:fonts.body},submit:{minHeight:54,borderRadius:16,backgroundColor:colors.pinkDeep,alignItems:'center',justifyContent:'center',marginTop:17},disabled:{opacity:.6},submitText:{color:'white',fontSize:13,fontFamily:fonts.bodyBold},success:{borderRadius:22,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,padding:22,alignItems:'center'},successMark:{width:52,height:52,borderRadius:26,backgroundColor:colors.pinkSoft,color:colors.pinkDeep,fontSize:25,fontFamily:fonts.heading,lineHeight:52,textAlign:'center'},successText:{color:colors.ink,fontSize:13,fontFamily:fonts.bodyBold,marginTop:14}});
