import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Screen } from '@/components/Screen';
import { FadeIn } from '@/components/motion/FadeIn';
import { SpringPressable } from '@/components/motion/SpringPressable';
import { tapFeedback } from '@/lib/feedback';
import { useAuth } from '@/providers/AuthProvider';
import { colors, fonts } from '@/theme';

export default function CommunityScreen(){
  const{membership}=useAuth();
  const member=membership?.status==='verified';
  return <Screen>
    <FadeIn delay={30}><Text style={styles.title}>Community</Text><Text style={styles.subtitle}>Your people. Your city. Your next gathering.</Text></FadeIn>
    <FadeIn delay={90}><View style={styles.hero}><View style={styles.heroOrbit}/><View style={styles.badge}><Text style={styles.badgeText}>{member?'MY COMMUNITY':'EXPLORE A COMMUNITY'}</Text></View><Text style={styles.heroTitle}>{member?'Lagos City Club':'GWMB in Lagos'}</Text><Text style={styles.heroCopy}>{member?'A community of ambitious women growing together.':'Discover events, Sister Circles and local sisterhood.'}</Text></View></FadeIn>
    <FadeIn delay={150}><View style={styles.sectionHead}><Text style={styles.sectionTitle}>Coming up</Text><Pressable onPress={()=>router.push('/events' as never)}><Text style={styles.link}>View all events</Text></Pressable></View><SpringPressable onPress={()=>{void tapFeedback();router.push('/event/progress-circle')}} style={styles.event}><View style={styles.eventMedia}><View style={styles.eventDate}><Text style={styles.eventDay}>31</Text><Text style={styles.eventMonth}>OCT</Text></View><Ionicons name="people" size={32} color="white"/></View><View style={styles.eventBody}><Text style={styles.kicker}>ACCOUNTABILITY CHECK-IN · MEMBERS ONLY</Text><Text style={styles.eventTitle}>October Progress Circle</Text><Text style={styles.eventCopy}>Reflect, reset and name your next committed action with the community.</Text><Text style={styles.link}>View event →</Text></View></SpringPressable></FadeIn>
    <FadeIn delay={220}><View style={styles.sectionHead}><Text style={styles.sectionTitle}>Latest update</Text><Text style={styles.link}>View all</Text></View><View style={styles.update}><View style={styles.updateIcon}><Ionicons name="megaphone-outline" size={20} color={colors.pinkDeep}/></View><View style={styles.updateCopy}><Text style={styles.updateTitle}>Volunteer team applications are open</Text><Text style={styles.updateText}>Help shape our October community outreach.</Text></View><Ionicons name="bookmark-outline" size={19} color={colors.muted}/></View></FadeIn>
    <FadeIn delay={280}><View style={styles.sectionHead}><Text style={styles.sectionTitle}>Get involved</Text></View><View style={styles.quickRow}><SpringPressable onPress={()=>{void tapFeedback();router.push('/events?tab=my' as never)}} style={styles.quick} contentStyle={styles.quickContent}><Ionicons name="calendar-outline" size={24} color={colors.pinkDeep}/><Text style={styles.quickTitle}>My Events</Text></SpringPressable><SpringPressable onPress={()=>void tapFeedback()} style={styles.quick} contentStyle={styles.quickContent}><Ionicons name="heart-outline" size={24} color={colors.pinkDeep}/><Text style={styles.quickTitle}>Volunteer</Text></SpringPressable></View></FadeIn>
  </Screen>
}

const styles=StyleSheet.create({title:{fontSize:30,fontFamily:fonts.heading,letterSpacing:-1.2,color:colors.ink,marginTop:8},subtitle:{fontSize:13,lineHeight:19,fontFamily:fonts.body,color:colors.muted,marginTop:7},hero:{minHeight:205,borderRadius:24,backgroundColor:colors.ink,padding:21,justifyContent:'flex-end',overflow:'hidden',marginTop:23},heroOrbit:{position:'absolute',right:-35,top:-40,width:170,height:170,borderRadius:85,borderWidth:30,borderColor:'rgba(230,43,127,.25)'},badge:{alignSelf:'flex-start',borderRadius:999,backgroundColor:'rgba(230,43,127,.22)',paddingHorizontal:10,paddingVertical:7},badgeText:{color:'#FFB0D4',fontSize:9,fontFamily:fonts.bodyBold,letterSpacing:.65},heroTitle:{color:'white',fontSize:25,fontFamily:fonts.heading,marginTop:11},heroCopy:{color:'#D7D0D4',fontSize:12,lineHeight:18,fontFamily:fonts.body,marginTop:6,maxWidth:280},sectionHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:26,marginBottom:11},sectionTitle:{color:colors.ink,fontSize:18,fontFamily:fonts.heading},link:{color:colors.pinkDeep,fontSize:11,fontFamily:fonts.bodyBold},event:{borderRadius:22,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,overflow:'hidden'},eventMedia:{height:135,backgroundColor:colors.pink,padding:16,flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between'},eventDate:{width:58,height:62,borderRadius:16,backgroundColor:'white',alignItems:'center',justifyContent:'center'},eventDay:{color:colors.pinkDeep,fontSize:23,fontFamily:fonts.heading},eventMonth:{color:colors.pinkDeep,fontSize:10,fontFamily:fonts.bodyBold,letterSpacing:.85},eventBody:{padding:15},kicker:{color:colors.pinkDeep,fontSize:9,fontFamily:fonts.bodyBold,letterSpacing:.55},eventTitle:{color:colors.ink,fontSize:17,fontFamily:fonts.headingBold,marginTop:6},eventCopy:{color:colors.muted,fontSize:11,lineHeight:17,fontFamily:fonts.body,marginTop:5,marginBottom:10},update:{minHeight:82,borderRadius:19,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,padding:13,flexDirection:'row',alignItems:'center'},updateIcon:{width:42,height:42,borderRadius:14,backgroundColor:colors.pinkSoft,alignItems:'center',justifyContent:'center'},updateCopy:{flex:1,minWidth:0,paddingHorizontal:11},updateTitle:{color:colors.ink,fontSize:12,fontFamily:fonts.headingBold},updateText:{color:colors.muted,fontSize:10,lineHeight:15,fontFamily:fonts.body,marginTop:4},quickRow:{flexDirection:'row',gap:10},quick:{flex:1,minHeight:105,borderRadius:20,backgroundColor:colors.pinkSoft,overflow:'hidden'},quickContent:{padding:15,justifyContent:'space-between'},quickTitle:{color:colors.ink,fontSize:13,fontFamily:fonts.headingBold}});
