import { Ionicons } from '@expo/vector-icons';
import { router, type Href, useFocusEffect } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Screen } from '@/components/Screen';
import { growCategories } from '@/data/grow';
import { colors, fonts } from '@/theme';
import { courses } from '@/data/courses';
import { coursePercent, loadCourseProgress, type CourseProgress } from '@/lib/course-progress';
import { useAuth } from '@/providers/AuthProvider';

export default function GrowScreen(){
  const[query,setQuery]=useState('');
  const[progress,setProgress]=useState<CourseProgress|null>(null);
  const{user}=useAuth(); const userId=user?.id; const cvCourse=courses['workplace-foundations'];
  useFocusEffect(useCallback(()=>{let active=true;if(!userId){setProgress(null);return()=>{active=false};}loadCourseProgress(userId,cvCourse.id).then(result=>{if(active)setProgress(result.progress)});return()=>{active=false};},[cvCourse.id,userId]));
  const percent=coursePercent(progress,cvCourse.lessons.length); const currentIndex=Math.max(0,cvCourse.lessons.findIndex(item=>!progress?.completed_lesson_ids.includes(item.id)));
  const visible=useMemo(()=>growCategories.filter(item=>`${item.title} ${item.description}`.toLowerCase().includes(query.trim().toLowerCase())),[query]);
  const cardTones=[styles.cardDark,styles.cardPink,styles.cardLavender,styles.cardCream,styles.cardPink,styles.cardDark];
  return <Screen><Text style={styles.eyebrow}>Your development</Text><Text style={styles.title}>Grow.</Text><Text style={styles.copy}>Build your career, skills and confidence.</Text><View style={styles.search}><Ionicons name="search" size={19} color={colors.muted}/><TextInput value={query} onChangeText={setQuery} placeholder="Search benefits and topics" placeholderTextColor="#9A9498" style={styles.input}/><View style={styles.filterIcon}><Ionicons name="options-outline" size={17} color={colors.ink}/></View></View><View style={styles.sectionHead}><Text style={styles.sectionTitle}>Explore your benefits</Text><Text style={styles.sectionLink}>My certificates</Text></View><View style={styles.grid}>{visible.map(item=>{const sourceIndex=growCategories.indexOf(item);const dark=sourceIndex===0||sourceIndex===5;return <Pressable key={item.slug} onPress={()=>router.push(`/grow/${item.slug}` as Href)} style={({pressed})=>[styles.card,cardTones[sourceIndex],pressed&&styles.cardPressed]}>{({pressed})=><><View style={[styles.icon,dark&&styles.iconDark,pressed&&styles.iconPressed]}><Ionicons name={item.icon} size={20} color={dark||pressed?'white':colors.pinkDeep}/></View><Text style={[styles.cardTitle,dark&&styles.white]}>{item.shortTitle}</Text><Text style={[styles.cardCopy,dark&&styles.darkMuted]}>{item.description}</Text></>}</Pressable>})}</View>{!visible.length?<View style={styles.empty}><Ionicons name="search-outline" size={26} color={colors.pinkDeep}/><Text style={styles.emptyTitle}>No matching benefit</Text><Text style={styles.emptyCopy}>Try “career”, “money” or “leadership”.</Text></View>:null}<View style={styles.sectionHead}><Text style={styles.sectionTitle}>Continue your growth</Text></View><Pressable onPress={()=>router.push('/course/workplace-foundations')} style={styles.continueCard}><View style={styles.continueIcon}><Ionicons name="play-circle-outline" size={22} color={colors.pinkDeep}/></View><View style={styles.continueCopy}><Text style={styles.continueTitle}>CV that gets noticed</Text><Text style={styles.continueMeta}>{progress?percent===100?'Complete · Certificate ready':`Lesson ${currentIndex+1} of ${cvCourse.lessons.length} · ${percent}%`:'Ready to start · 6 lessons'}</Text></View><View style={styles.arrowButton}><Ionicons name="arrow-forward" size={17} color="white"/></View></Pressable></Screen>
}

const styles=StyleSheet.create({eyebrow:{color:colors.pinkDeep,fontSize:9,fontFamily:fonts.bodyBold,letterSpacing:1.2,textTransform:'uppercase',marginTop:8},title:{fontSize:32,lineHeight:36,fontFamily:fonts.heading,color:colors.ink,letterSpacing:-1.2,marginTop:6},copy:{fontSize:12,lineHeight:18,fontFamily:fonts.body,color:colors.muted,marginTop:5},search:{height:52,borderRadius:17,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,flexDirection:'row',alignItems:'center',paddingLeft:14,marginTop:22},input:{flex:1,minWidth:0,height:'100%',paddingHorizontal:10,color:colors.ink,fontSize:11,fontFamily:fonts.body},filterIcon:{width:38,height:38,borderRadius:13,backgroundColor:'#F0EDEF',alignItems:'center',justifyContent:'center',marginRight:6},sectionHead:{width:'100%',flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:27,marginBottom:12},sectionTitle:{flexShrink:1,color:colors.ink,fontSize:17,fontFamily:fonts.heading},sectionLink:{flexShrink:0,color:colors.pinkDeep,fontSize:9,fontFamily:fonts.bodyBold},grid:{width:'100%',flexDirection:'row',flexWrap:'wrap',gap:10},card:{width:'48%',maxWidth:'48%',minWidth:0,minHeight:132,borderRadius:20,padding:15,overflow:'hidden'},cardDark:{backgroundColor:colors.ink},cardPink:{backgroundColor:colors.pinkSoft},cardLavender:{backgroundColor:'#F0EFFF'},cardCream:{backgroundColor:'#FFF4DF'},cardPressed:{opacity:.88,transform:[{translateY:-2}]},icon:{width:36,height:36,borderRadius:18,backgroundColor:'rgba(230,43,127,.14)',alignItems:'center',justifyContent:'center'},iconDark:{backgroundColor:colors.pink},iconPressed:{backgroundColor:colors.pinkDeep},cardTitle:{color:colors.ink,fontSize:13,lineHeight:16,fontFamily:fonts.headingBold,marginTop:17},cardCopy:{flexShrink:1,color:colors.muted,fontSize:9,lineHeight:12,fontFamily:fonts.body,marginTop:6,maxWidth:130},white:{color:'white'},darkMuted:{color:'#AAA4A8'},empty:{borderRadius:20,backgroundColor:colors.pinkSoft,padding:24,alignItems:'center'},emptyTitle:{color:colors.ink,fontSize:14,fontFamily:fonts.headingBold,marginTop:9},emptyCopy:{color:colors.muted,fontSize:10,fontFamily:fonts.body,marginTop:4},continueCard:{width:'100%',minHeight:82,borderRadius:19,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,padding:13,flexDirection:'row',alignItems:'center'},continueIcon:{width:46,height:46,borderRadius:13,backgroundColor:colors.pinkSoft,alignItems:'center',justifyContent:'center'},continueCopy:{flex:1,minWidth:0,paddingHorizontal:12},continueTitle:{color:colors.ink,fontSize:12,fontFamily:fonts.headingBold},continueMeta:{color:colors.muted,fontSize:9,fontFamily:fonts.body,marginTop:5},arrowButton:{width:34,height:34,borderRadius:17,backgroundColor:colors.ink,alignItems:'center',justifyContent:'center'}});
