import { Ionicons } from '@expo/vector-icons';
import { router as expoRouter } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { Screen } from '@/components/Screen';
import { useAuth } from '@/providers/AuthProvider';
import { colors, fonts } from '@/theme';

const router = { push: (href: string) => expoRouter.push(href as never) };

const rows=[['My Membership','card-outline','/membership'],['My Events','calendar-outline','/events?tab=my'],['My GWMB Activity','trending-up-outline','/activity'],['Settings','settings-outline','/settings'],['Help & Support','help-circle-outline','/help']] as const;

export default function ProfileScreen(){
  const { user, profile, membership, loading, signOut } = useAuth();
  const [signingOut,setSigningOut]=useState(false);
  const fullName=profile?.full_name || user?.email?.split('@')[0] || 'GWMB Girlie';
  const initials=fullName.split(' ').filter(Boolean).slice(0,2).map(part=>part[0]).join('').toUpperCase();
  const membershipLabel=membership?.status==='verified'?'Active Member':membership?.status==='pending'?'Membership verification pending':'Guest account';
  async function handleSignOut(){setSigningOut(true);try{await signOut();}finally{setSigningOut(false);}}

  if(loading)return <Screen scroll={false}><View style={styles.loading}><ActivityIndicator color={colors.pinkDeep}/></View></Screen>;
  if(!user)return <Screen><View style={styles.guestHero}><View style={styles.guestIcon}><Ionicons name="person-outline" size={31} color={colors.pinkDeep}/></View><Text style={styles.guestTitle}>Your GWMB journey, saved.</Text><Text style={styles.guestCopy}>Sign in to continue courses, save opportunities and verify your membership.</Text><Pressable onPress={()=>router.push('/sign-in')} style={styles.primary}><Text style={styles.primaryText}>Sign in</Text></Pressable><Pressable onPress={()=>router.push('/sign-up')} style={styles.secondary}><Text style={styles.secondaryText}>Create an account</Text></Pressable><Pressable onPress={()=>router.push('/membership')}><Text style={styles.membershipLink}>Explore membership benefits</Text></Pressable></View></Screen>;

  return <Screen><View style={styles.head}><View style={styles.avatar}>{profile?.avatar_url?<Image source={{uri:profile.avatar_url}} style={styles.avatarImage}/>:<Text style={styles.initials}>{initials}</Text>}{membership?.status==='verified'?<View style={styles.online}/>:null}</View><Text style={styles.name}>{fullName}</Text><Text style={styles.email}>{user.email}</Text><View style={[styles.status,membership?.status==='verified'&&styles.statusVerified]}><Text style={[styles.statusText,membership?.status==='verified'&&styles.statusTextVerified]}>{membershipLabel}</Text></View><Pressable onPress={()=>router.push('/edit-profile')} style={styles.edit}><Text style={styles.editText}>Edit profile</Text></Pressable></View><View style={styles.menu}>{rows.map(([label,icon,route])=><Pressable key={label} onPress={()=>router.push(route)} style={styles.row}><View style={styles.rowIcon}><Ionicons name={icon} size={19} color={colors.pinkDeep}/></View><Text style={styles.rowText}>{label}</Text><Ionicons name="chevron-forward" size={18} color={colors.muted}/></Pressable>)}</View><Pressable disabled={signingOut} onPress={handleSignOut} style={styles.signOut}>{signingOut?<ActivityIndicator color={colors.pinkDeep}/>:<><Ionicons name="log-out-outline" size={19} color={colors.pinkDeep}/><Text style={styles.signOutText}>Sign out</Text></>}</Pressable></Screen>;
}

const styles=StyleSheet.create({loading:{flex:1,alignItems:'center',justifyContent:'center'},guestHero:{marginTop:35,padding:24,borderRadius:26,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,alignItems:'center'},guestIcon:{width:70,height:70,borderRadius:24,backgroundColor:colors.pinkSoft,alignItems:'center',justifyContent:'center'},guestTitle:{color:colors.ink,fontSize:23,lineHeight:28,fontFamily:fonts.heading,textAlign:'center',letterSpacing:-.8,marginTop:20},guestCopy:{color:colors.muted,fontSize:11,lineHeight:18,fontFamily:fonts.body,textAlign:'center',marginTop:8,maxWidth:285},primary:{minHeight:52,borderRadius:16,backgroundColor:colors.pinkDeep,alignSelf:'stretch',alignItems:'center',justifyContent:'center',marginTop:23},primaryText:{color:'white',fontSize:12,fontFamily:fonts.heading},secondary:{minHeight:50,borderRadius:16,borderWidth:1,borderColor:colors.line,alignSelf:'stretch',alignItems:'center',justifyContent:'center',marginTop:10},secondaryText:{color:colors.ink,fontSize:12,fontFamily:fonts.bodyBold},membershipLink:{color:colors.pinkDeep,fontSize:10,fontFamily:fonts.bodyBold,marginTop:20},head:{alignItems:'center',paddingTop:12,paddingBottom:25},avatar:{width:82,height:82,borderRadius:41,backgroundColor:colors.ink,alignItems:'center',justifyContent:'center'},avatarImage:{width:82,height:82,borderRadius:41},initials:{color:'white',fontSize:24,fontFamily:fonts.heading},online:{position:'absolute',right:3,bottom:5,width:16,height:16,borderRadius:8,backgroundColor:colors.green,borderWidth:3,borderColor:colors.canvas},name:{color:colors.ink,fontSize:22,fontFamily:fonts.heading,marginTop:14,textTransform:'capitalize'},email:{color:colors.muted,fontSize:10,fontFamily:fonts.body,marginTop:4},status:{backgroundColor:colors.pinkSoft,borderRadius:999,paddingHorizontal:10,paddingVertical:6,marginTop:10},statusVerified:{backgroundColor:'#E5F6EF'},statusText:{color:colors.pinkDeep,fontSize:9,fontFamily:fonts.bodyBold},statusTextVerified:{color:'#087553'},edit:{marginTop:14,minHeight:38,paddingHorizontal:18,borderRadius:12,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,justifyContent:'center'},editText:{color:colors.ink,fontSize:11,fontFamily:fonts.bodyBold},menu:{borderRadius:22,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,overflow:'hidden'},row:{minHeight:68,paddingHorizontal:15,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:colors.line},rowIcon:{width:37,height:37,borderRadius:12,backgroundColor:colors.pinkSoft,alignItems:'center',justifyContent:'center'},rowText:{flex:1,color:colors.ink,fontSize:13,fontFamily:fonts.bodyBold,marginLeft:12},signOut:{minHeight:52,borderRadius:16,borderWidth:1,borderColor:colors.line,marginTop:16,flexDirection:'row',gap:8,alignItems:'center',justifyContent:'center'},signOutText:{color:colors.pinkDeep,fontSize:11,fontFamily:fonts.heading}});
