import { Ionicons } from '@expo/vector-icons';
import { router as expoRouter, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { useCallback, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { PageHeader } from '@/components/PageHeader';
import { Screen } from '@/components/Screen';
import { opportunityById } from '@/data/opportunities';
import { loadSavedOpportunityIds, setOpportunitySaved } from '@/lib/opportunity-store';
import { useAuth } from '@/providers/AuthProvider';
import { colors, fonts } from '@/theme';

const router={push:(href:string)=>expoRouter.push(href as never)};

export default function OpportunityDetail(){
  const{id}=useLocalSearchParams<{id:string}>();
  const{user,membership}=useAuth();
  const item=opportunityById[id]??opportunityById.flutterwave;
  const[saved,setSaved]=useState(false);
  useFocusEffect(useCallback(()=>{let active=true;loadSavedOpportunityIds(user?.id).then(ids=>{if(active)setSaved(ids.includes(item.id))});return()=>{active=false};},[item.id,user?.id]));
  async function toggleSaved(){const next=!saved;setSaved(next);await setOpportunitySaved(user?.id,item.id,next);}
  function apply(){if(!user){router.push('/sign-in');return;}if(item.access==='Members Only'&&membership?.status!=='verified'){router.push('/membership');return;}router.push(`/application/opportunity?opportunityId=${item.id}`);}
  const ctaLabel=!user?'Sign in to apply':item.access==='Members Only'&&membership?.status!=='verified'?'Explore Membership':'Apply Now';
  return <Screen><PageHeader title="Opportunity"/><View style={styles.media}><View style={styles.brand}><Text style={styles.brandText}>{item.initials}</Text></View><View style={styles.mediaCopy}><Text style={styles.mediaLabel}>{item.source}</Text><Text style={styles.mediaOrg}>{item.org}</Text></View><Ionicons name="sparkles" size={25} color="#FFD100" style={styles.spark}/></View><View style={styles.actionRow}><View style={styles.badges}><View style={styles.source}><Text style={styles.sourceText}>{item.source}</Text></View><View style={item.access==='Open Access'?styles.open:styles.member}><Text style={item.access==='Open Access'?styles.openText:styles.memberText}>{item.access}</Text></View></View><Pressable onPress={()=>void toggleSaved()} style={[styles.save,saved&&styles.saveActive]}><Ionicons name={saved?'bookmark':'bookmark-outline'} size={17} color={saved?'white':colors.ink}/><Text style={[styles.saveText,saved&&styles.saveTextActive]}>{saved?'Saved':'Save'}</Text></Pressable></View><Text style={styles.title}>{item.title}</Text><Text style={styles.copy}>{item.summary}</Text><View style={styles.facts}><View style={styles.fact}><Ionicons name="location-outline" size={20} color={colors.pinkDeep}/><View><Text style={styles.factLabel}>LOCATION</Text><Text style={styles.factValue}>{item.location}</Text></View></View><View style={styles.fact}><Ionicons name="calendar-outline" size={20} color={colors.pinkDeep}/><View><Text style={styles.factLabel}>DEADLINE</Text><Text style={styles.factValue}>{item.deadline}</Text></View></View></View><Text style={styles.section}>About the opportunity</Text><Text style={styles.sectionCopy}>Work on meaningful projects, learn from experienced professionals and build evidence of your skills in a supportive environment.</Text><Text style={styles.section}>What you’ll need</Text>{['Current CV or professional profile','A thoughtful motivation response','Portfolio or LinkedIn link where relevant'].map(point=><View key={point} style={styles.point}><Ionicons name="checkmark" size={15} color={colors.pinkDeep}/><Text style={styles.pointText}>{point}</Text></View>)}<Pressable onPress={apply} style={styles.cta}><Text style={styles.ctaText}>{ctaLabel}</Text><Ionicons name="arrow-forward" size={18} color="white"/></Pressable></Screen>;
}

const styles=StyleSheet.create({media:{height:150,borderRadius:23,backgroundColor:colors.ink,padding:18,flexDirection:'row',alignItems:'center',gap:13,overflow:'hidden'},brand:{width:61,height:61,borderRadius:19,backgroundColor:'white',alignItems:'center',justifyContent:'center'},brandText:{color:colors.pinkDeep,fontSize:18,fontFamily:fonts.heading},mediaCopy:{flex:1},mediaLabel:{color:'#F0A3C7',fontSize:9,fontFamily:fonts.bodyBold,letterSpacing:.7},mediaOrg:{color:'white',fontSize:16,fontFamily:fonts.headingBold,marginTop:5},spark:{position:'absolute',right:17,top:17},actionRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:18},badges:{flexDirection:'row',gap:7},source:{backgroundColor:'#EDEFFF',borderRadius:999,paddingHorizontal:9,paddingVertical:6},sourceText:{color:'#3540C6',fontSize:9,fontFamily:fonts.bodyBold},open:{backgroundColor:'#E4F7EF',borderRadius:999,paddingHorizontal:9,paddingVertical:6},openText:{color:'#087553',fontSize:9,fontFamily:fonts.bodyBold},member:{backgroundColor:colors.pinkSoft,borderRadius:999,paddingHorizontal:9,paddingVertical:6},memberText:{color:colors.pinkDeep,fontSize:9,fontFamily:fonts.bodyBold},save:{height:34,borderRadius:12,backgroundColor:'#EEECEF',paddingHorizontal:10,flexDirection:'row',gap:5,alignItems:'center'},saveActive:{backgroundColor:colors.pinkDeep},saveText:{fontSize:9,fontFamily:fonts.bodyBold,color:colors.ink},saveTextActive:{color:'white'},title:{color:colors.ink,fontSize:25,lineHeight:29,fontFamily:fonts.heading,letterSpacing:-.9,marginTop:12},copy:{color:colors.muted,fontSize:11,lineHeight:18,fontFamily:fonts.body,marginTop:8},facts:{gap:9,marginTop:19},fact:{minHeight:65,borderRadius:17,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,paddingHorizontal:14,flexDirection:'row',alignItems:'center',gap:12},factLabel:{color:colors.pinkDeep,fontSize:9,fontFamily:fonts.bodyBold,letterSpacing:.7},factValue:{color:colors.ink,fontSize:10,fontFamily:fonts.bodyBold,marginTop:4},section:{color:colors.ink,fontSize:16,fontFamily:fonts.headingBold,marginTop:23},sectionCopy:{color:colors.muted,fontSize:10,lineHeight:17,fontFamily:fonts.body,marginTop:6},point:{minHeight:43,flexDirection:'row',alignItems:'center',gap:9,borderBottomWidth:1,borderBottomColor:colors.line},pointText:{color:colors.ink,fontSize:10,fontFamily:fonts.bodyMedium},cta:{minHeight:54,borderRadius:16,backgroundColor:colors.pinkDeep,paddingHorizontal:17,flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:22},ctaText:{color:'white',fontSize:12,fontFamily:fonts.bodyBold}});
